# Generated by Django 2.2.6 on 2019-10-22 14:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('scope', models.TextField(primary_key=True, serialize=False)),
                ('lineage', models.UUIDField(editable=False)),
                ('serial', models.IntegerField(editable=False)),
                ('version', models.IntegerField(editable=False)),
                ('terraform_version', models.TextField(editable=False)),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('scope', 'lineage', 'serial')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(editable=False)),
                ('type', models.TextField(editable=False)),
                ('module', models.TextField(editable=False, null=True)),
                ('name', models.TextField(editable=False)),
                ('provider', models.TextField(editable=False)),
                ('each', models.TextField(editable=False, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.State')),
            ],
            options={
                'unique_together': {('state', 'type', 'module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.State')),
            ],
            options={
                'unique_together': {('state', 'path')},
            },
        ),
        migrations.CreateModel(
            name='V3Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(editable=False)),
                ('depends_on', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('primary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('provider', models.TextField(editable=False)),
                ('type', models.TextField(editable=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.Module')),
            ],
            options={
                'unique_together': {('module', 'key'), ('module', 'type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.IntegerField(editable=False)),
                ('index_key', models.IntegerField(editable=False, null=True)),
                ('attribute_id', models.TextField(editable=False)),
                ('private', models.TextField(editable=False)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('depends_on', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.Resource')),
            ],
            options={
                'unique_together': {('resource', 'index_key'), ('resource', 'index_key', 'attribute_id')},
            },
        ),
    ]
